services:
  postgres-db:
    image: "postgres:14.2-alpine"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - postgres-db-vol:/var/lib/postgresql/data
    ports:
      - 5432:5432 # host:container
    networks:
    - backend

  server:
    build: .
    restart: always
    environment:
      #DATABASE_HOST: postgres-db # faut que ce soit le hostname de la database
      DATABASE_HOST: postgres-db # faut que ce soit le hostname de la database
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWD: mysecretpassword
    ports:
      - 8080:8080 # host:container
    networks:
      - backend

volumes:
  postgres-db-vol:
    driver: local

networks:
  backend:
